### ISSUE TITLE
Architectural Design for the Application

### ISSUE THREAD

**Issue by mdnazisharman2803** [mdnazisharman2803/The-Savvy-Dart#2]
Implement design of the website using using Figma/Adobe
- On Boarding Screens
- Login Screen
- Signup Screen
- Home screen

Once the design is ready kindly add in readme file

**Comment by spike-spiegel-21** [comment]
I have designed my college website, I will be able to design the listed components in Figma, please assign me this task. Thank you.

**Comment by misteral1009** [comment]
Let's go

**Comment by misteral1009** [comment]
let's go
